### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by delanym** [caius/bundler-native-gems#7]
```
gem install bundler-native-gems
bundler native-gems
```

```
/var/lib/gems/3.2.0/gems/bundler-1.17.3/lib/bundler/shared_helpers.rb:272:in `search_up': undefined method `untaint' for "/home/sol/tester":String (NoMethodError)

      current  = File.expand_path(SharedHelpers.pwd).untaint
                                                    ^^^^^^^^
        from /var/lib/gems/3.2.0/gems/bundler-1.17.3/lib/bundler/shared_helpers.rb:259:in `find_file'
        from /var/lib/gems/3.2.0/gems/bundler-1.17.3/lib/bundler/shared_helpers.rb:251:in `find_gemfile'
        from /var/lib/gems/3.2.0/gems/bundler-1.17.3/lib/bundler/shared_helpers.rb:27:in `root'
        from /var/lib/gems/3.2.0/gems/bundler-1.17.3/lib/bundler.rb:234:in `root'
        from /var/lib/gems/3.2.0/gems/bundler-1.17.3/lib/bundler.rb:246:in `app_config_path'
        from /var/lib/gems/3.2.0/gems/bundler-1.17.3/lib/bundler.rb:273:in `settings'
        from /var/lib/gems/3.2.0/gems/bundler-1.17.3/lib/bundler/feature_flag.rb:21:in `block in settings_method'
        from /var/lib/gems/3.2.0/gems/bundler-1.17.3/lib/bundler/cli.rb:97:in `<class:CLI>'
        from /var/lib/gems/3.2.0/gems/bundler-1.17.3/lib/bundler/cli.rb:7:in `<module:Bundler>'
        from /var/lib/gems/3.2.0/gems/bundler-1.17.3/lib/bundler/cli.rb:6:in `<top (required)>'
        from <internal:/usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb>:86:in `require'
        from <internal:/usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb>:86:in `require'
        from /var/lib/gems/3.2.0/gems/bundler-native-gems-1.0.0/exe/bundler-native-gems:15:in `<top (required)>'
        from /usr/local/bin/bundler-native-gems:25:in `load'
        from /usr/local/bin/bundler-native-gems:25:in `<main>'
```

ruby 3.2.3 (2024-01-18 revision 52bb2ac0a6) [x86_64-linux-gnu]
Bundler version 2.4.19

**Comment by caius** [comment]
Interesting, looking into this it appears to be an issue between Bundler 1.17.x and Ruby > 3. I think I've accidentally left the gem dependencies pinned to an earlier bundler, so it might not be executing in a bundle version that your app dependencies are using.

More specifically it seems Bundler 1.17.3 doesn't work on Ruby newer than 3.1.x due to Ruby 3.2.0 removing `String#untaint`. The advice from bundler is to upgrade to Bundler 2 in those situations.

I think I'm going to update this to work against Bundler 1 or Bundler 2 and drop the dependency on a specific version of bundler to fix it.

**Comment by delanym** [comment]
@caius any luck?
